POST http://localhost:3333/events
Content-Type: application/json

{
    "title":"NLW 123",
    "details":"qualquer coisa",
    "maximumattendees":1
}
###
POST http://localhost:3333/events/078a6f7f-864d-4071-b599-24d27d1d5865/attendee
Content-Type: application/json

{
    "name":"Margarida Diamantino",
    "email":"margaridadiamantino78@gmail.com"
}
###
GET http://localhost:3333/events/078a6f7f-864d-4071-b599-24d27d1d5865

###
GET http://localhost:3333/attendees/6/badge

###
GET http://localhost:3333/attendees/7/check-in

###
GET http://localhost:3333/events/078a6f7f-864d-4071-b599-24d27d1d5865/attendees

